 //LDSRUN JOB (EMC),'ASMBUILD',CLASS=A,MSGCLASS=X, 
 //           NOTIFY=&SYSUID,REGION=0M,MSGLEVEL=(1,1) 
 //RUNPROG EXEC PGM=HI 
 //STEPLIB DD DSN=FAGUS.DEV.LOADLIB,DISP=SHR 
 //SYSPRINT DD SYSOUT=* 
 //SNAPDD DD SYSOUT=* 
 // 
